// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbeykultwcpaplmaquur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZXlrdWx0d2NwYXBsbWFxdXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDI4MTUsImV4cCI6MjA3MjMxODgxNX0._V-IBx3gwG8JZv7mGnhemXI-vxaxAw4iffPn4sHIers";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});