// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofgmixalwkegtsqppmre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mZ21peGFsd2tlZ3RzcXBwbXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mzg4MDQsImV4cCI6MjA3MjMxNDgwNH0.-kdSMtxzHhtkWDHq2fOGrRveCEKB6NFwRG6s57e0Nms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});